runtime: nodejs16 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "gcs-bucket"

handlers:
- url: /playstem
  static_dir: playstem

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto